version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE= "on"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run: echo "Success"
