---
version: "2.4"

services:
  client:
    build:
      context: ../
      dockerfile: ./Dockerfile.toolbox
    volumes:
      - ../:/go/src/github.com/jlevesy/go-sind
      - ../.gocache/mod:/go/pkg/mod
      - ../.gocache/build:/go/.cache/go-build
    environment:
      DOCKER_HOST: tcp://dind:2375
    depends_on:
      - dind
    command:
      - go
      - test
      - -count=1
      - -v
      - ./integration

  dind:
    image: docker:dind
    privileged: true
